# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1252, 920)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setHorizontalSpacing(41)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.combo_interface = QtWidgets.QComboBox(self.centralwidget)
        self.combo_interface.setObjectName("combo_interface")
        self.gridLayout.addWidget(self.combo_interface, 1, 1, 1, 2)
        self.radio_length = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_length.sizePolicy().hasHeightForWidth())
        self.radio_length.setSizePolicy(sizePolicy)
        self.radio_length.setAutoExclusive(False)
        self.radio_length.setObjectName("radio_length")
        self.gridLayout.addWidget(self.radio_length, 11, 2, 1, 1)
        self.radio_ip = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_ip.sizePolicy().hasHeightForWidth())
        self.radio_ip.setSizePolicy(sizePolicy)
        self.radio_ip.setAutoExclusive(False)
        self.radio_ip.setObjectName("radio_ip")
        self.gridLayout.addWidget(self.radio_ip, 11, 0, 1, 1)
        self.radio_protocol = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_protocol.sizePolicy().hasHeightForWidth())
        self.radio_protocol.setSizePolicy(sizePolicy)
        self.radio_protocol.setChecked(True)
        self.radio_protocol.setAutoExclusive(False)
        self.radio_protocol.setObjectName("radio_protocol")
        self.gridLayout.addWidget(self.radio_protocol, 7, 0, 1, 1)
        self.radio_packet = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_packet.sizePolicy().hasHeightForWidth())
        self.radio_packet.setSizePolicy(sizePolicy)
        self.radio_packet.setChecked(True)
        self.radio_packet.setAutoExclusive(False)
        self.radio_packet.setObjectName("radio_packet")
        self.gridLayout.addWidget(self.radio_packet, 7, 2, 1, 1)
        self.graphics_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphics_view.setObjectName("graphics_view")
        self.gridLayout.addWidget(self.graphics_view, 4, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 4)
        self.label_interface = QtWidgets.QLabel(self.centralwidget)
        self.label_interface.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_interface.setObjectName("label_interface")
        self.gridLayout.addWidget(self.label_interface, 1, 0, 1, 1)
        self.netspeed_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.netspeed_label.sizePolicy().hasHeightForWidth())
        self.netspeed_label.setSizePolicy(sizePolicy)
        self.netspeed_label.setObjectName("netspeed_label")
        self.gridLayout.addWidget(self.netspeed_label, 7, 3, 6, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "流量监控软件"))
        self.radio_length.setText(_translate("MainWindow", "单位：报文段大小"))
        self.radio_ip.setText(_translate("MainWindow", "显示 IP"))
        self.radio_protocol.setText(_translate("MainWindow", "显示传输协议"))
        self.radio_packet.setText(_translate("MainWindow", "单位：报文段数量"))
        self.label_interface.setText(_translate("MainWindow", "选择网卡："))
        self.netspeed_label.setText(_translate("MainWindow", "当前网速："))
